[package]
name = "netpulse"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
printpdf = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
plotly = "0.5"     # or the appropriate version for your project
rusqlite = "0.30"
r2d2 = "0.8"
r2d2_sqlite = "0.23"
reqwest = { version = "0.11", features = [ "json", "blocking", "rustls-tls"]}


[build-dependencies]
cargo-deb = "1.36"
#cargo-rpm = "^0.1"