[package]
name = "netpulse"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
#sqlx = { version = "0.5", features = ["sqlite", "runtime-tokio-rustls"] }
printpdf = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
#chart.js = "3.7"  # or the appropriate version for your project
plotly = "0.5"     # or the appropriate version for your project
rusqlite = "0.30"
r2d2 = "0.8"
r2d2_sqlite = "0.23"

[build-dependencies]
cargo-deb = "1.36"
#cargo-rpm = "^0.1"