[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest"
xargo = false
pre-build = [
    "apt-get update",
    "apt-get install -y libsqlite3-dev"
]

[target.armv7-unknown-linux-gnueabihf.env]
PKG_CONFIG_PATH = "/usr/lib/arm-linux-gnueabihf/pkgconfig"
SQLITE3_LIB_DIR = "/usr/lib/arm-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
xargo = false
pre-build = [
    "apt-get update",
    "apt-get install -y libsqlite3-dev"
]

[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
SQLITE3_LIB_DIR = "/usr/lib/aarch64-linux-gnu"